/** Auto-generated by CI/CD at Mon Apr 20 05:34:03 UTC 2026 */
const CONFIG = {
    apiUrl: 'https://api.placeholder.com',
    thresholds: { ppm: 500, monthlyTarget: 4500000, defectLimit: 80, capMin: 410 }
};
