/** Auto-generated by CI/CD at Tue Apr 21 04:51:26 UTC 2026 */
const CONFIG = {
    apiUrl: 'https://script.google.com/macros/s/AKfycbzebbOMTwtscn23_-vao0hLCmtLYdDVPOQxj33DMuG5p6o5Hcuz2Tlb1hGokXNRtKrW/exec',
    thresholds: { ppm: 500, monthlyTarget: 4500000, defectLimit: 80, capMin: 410 }
};
